apiVersion: source.toolkit.fluxcd.io/v1beta3
kind: HelmRepository
metadata:
  name: cnpg
  namespace: flux-system
spec:
  interval: 10m
  url: https://cloudnative-pg.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cnpg-operator
  namespace: flux-system
spec:
  interval: 10m
  chart:
    spec:
      chart: cloudnative-pg
      version: "0.20.0"
      sourceRef:
        kind: HelmRepository
        name: cnpg
  install:
    createNamespace: true
  targetNamespace: cnpg-system
