apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: n8n
  namespace: production
spec:
  chart:
    spec:
      chart: n8n
      version: 0.0.3
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  interval: 1m
  values:
    replicaCount: 2
    image:
      repository: n8nio/n8n
      tag: latest
    database:
      host: cloudnative-pg.production.svc.cluster.local
      port: 5432
      user: n8n
      password: n8npass
