apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: n8n
  namespace: staging
spec:
  chart:
    spec:
      chart: ./charts/n8n
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  interval: 1m
  values:
    replicaCount: 1
    image:
      repository: n8nio/n8n
      tag: latest
    env:
      - name: DB_TYPE
        value: postgres
      - name: DB_POSTGRES_HOST
        value: n8n-staging-db-rw.staging.svc.cluster.local
      - name: DB_POSTGRES_DB
        value: n8n
      - name: DB_POSTGRES_USER
        value: n8n
      - name: DB_POSTGRES_PASSWORD
        value: n8npass
      - name: N8N_SECURE_COOKIE
        value: "false"

    ingress:
      enabled: true
      ingressClassName: traefik
      hostname: n8n.staging.127.0.0.1.sslip.io
      path: /
