apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: n8n
  namespace: staging
spec:
  chart:
    spec:
      chart: n8n
      version: 0.0.1
      sourceRef:
        kind: GitRepository
        name: infra-repo
        namespace: flux-system
  values:
    replicaCount: 1
    image:
      repository: n8nio/n8n
      tag: latest
    database:
      host: cloudnative-pg.production.svc.cluster.local
      port: 5432
      user: n8n
      password: n8npass
