apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: n8n
  namespace: production
spec:
  chart:
    spec:
      chart: ./charts/n8n
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  interval: 1m
  values:
    replicaCount: 2
    image:
      repository: n8nio/n8n
      tag: latest
    env:
      - name: DB_TYPE
        value: postgres
      - name: DB_POSTGRES_HOST
        value: n8n-prod-db-rw.production.svc.cluster.local
      - name: DB_POSTGRES_DB
        value: n8n
      - name: DB_POSTGRES_USER
        value: n8n
      - name: DB_POSTGRES_PASSWORD
        value: n8npass
    ingress:
      enabled: true
      ingressClassName: traefik
      hostname: n8n.production.127.0.0.1.sslip.io
      path: /
    autoscaling:
      enabled: true
      minReplicas: 2
      maxReplicas: 5
      targetCPUUtilizationPercentage: 70
