apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cloudnative-pg
  namespace: flux-system
spec:
  releaseName: cloudnative-pg
  interval: 5m
  chart:
    spec:
      chart: cloudnative-pg
      version: "1.17.0"
      sourceRef:
        kind: HelmRepository
        name: cloudnative-pg
  values:
    replicaCount: 1
    postgresql:
      password: mysecretpassword
